language: python3
python:
  - "3.7.2"
cache: pip
install:
  - pip3 install -r requirements.txt && pip3 install PySAIS==1.0.4 && python3 setup.py install
branches:
  only:
    - dev
script:
  - make test
